artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/raghuramadivi/Chicken-Diesease-Classification-Project/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/Chicken-fecal-images.zip
  unzip_dir: artifacts/data_ingestion
